{% set version = "2.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fedmatch
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fedmatch_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fedmatch/fedmatch_{{ version }}.tar.gz
  sha256: b9a4dc092fd4774ebe76311a1cd09330937abb0d260f9e5f8c2b8eae373ecb1d

build:
  missing_dso_whitelist:
    - '*/R.dll'  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ stdlib("c") }}        # [not win]
    - {{ stdlib("m2w64_c") }}  # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - llvm-openmp                  # [osx]
    - libgomp                      # [not osx]
  host:
    - llvm-openmp                  # [osx]
    - libgomp                      # [not osx]
    - r-base
    - r-bh
    - r-rcpp
    - r-snowballc
    - r-data.table
    - r-forcats
    - r-magrittr
    - r-purrr
    - r-scales
    - r-stringdist
    - r-stringr
  run:
    - libgomp                      # [win]
    - r-base
    - r-rcpp
    - r-snowballc
    - r-data.table
    - r-forcats
    - r-magrittr
    - r-purrr
    - r-scales
    - r-stringdist
    - r-stringr

test:
  commands:
    - $R -e "library('fedmatch')"           # [not win]
    - "\"%R%\" -e \"library('fedmatch')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fedmatch
  license: MIT
  summary: 'Provides a flexible set of tools for matching two un-linked data sets. ''fedmatch'' allows for three ways to match data: exact matches, fuzzy matches, and multi-variable matches. It also allows an easy combination of these three matches via the tier matching function.'
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - JNuss71

# Package: fedmatch
# Title: Fast, Flexible, and User-Friendly Record Linkage Methods
# Version: 2.0.6
# Authors@R: c(person("Melanie", "Friedrichs", email = "melanie.r.friedrichs@gmail.com", role = c("aut")), person("Chris", "Webster", email = "chris0webster@gmail.com", role = c("aut", "cre")), person("Blake", "Marsh", email = "blake.marsh@kc.frb.org", role = c("aut")), person("Jacob", "Dice", email = "Jacob.Dice@kc.frb.org", role = c("aut")), person("Seung", "Lee", email = "seung.j.lee@frb.gov", role = c("aut")))
# Description: Provides a flexible set of tools for matching two un-linked data sets. 'fedmatch' allows for three ways to match data: exact matches, fuzzy matches, and multi-variable matches. It also allows an easy combination of these three matches via the tier matching function.
# Depends: R (>= 3.5.3)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Imports: stringdist, SnowballC, stringr, purrr, Rcpp, parallel, forcats, data.table, magrittr, scales
# RoxygenNote: 7.2.3
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# LinkingTo: Rcpp, BH
# NeedsCompilation: yes
# Packaged: 2024-05-20 00:16:53 UTC; chriswebster
# Author: Melanie Friedrichs [aut], Chris Webster [aut, cre], Blake Marsh [aut], Jacob Dice [aut], Seung Lee [aut]
# Maintainer: Chris Webster <chris0webster@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-05-20 02:10:02 UTC
